### ISSUE TITLE
publish on hex.pm?

### ISSUE THREAD

**Issue by matteosister** [Around25/eximap#1] opened 2018-02-15 17:03 UTC
Hello everybody,
Do you have any plans on publishing this library on hex.pm?

Many thanks in advance.

**Comment by cosmin-harangus** [comment] 2018-02-15 18:23
Hi Matteo,

Yes, we are planning on releasing it to hex as soon as we finish converting the raw data into a structured format easy to consume by applications.

If you need a hex package we can release it sooner, but I would prefer to add it only after it is complete and documented first.

Please note that you can also use it in your Elixir applications using the git repo/branch as shown in the Mix documentation.

Best regards,

Cosmin Harangus
Technical Director

Around25

Phone: +40 726 74 06 60
Email: cosmin@around25.com
Web: www.around25.com

Address:
25 Cristea Nicolae,
Cluj Napoca, Cluj, 400184
Romania
This message is the property of Around 25 or its affiliates. It may be legally privileged and/or confidential and is intended only for the use of the addressee(s). No addressee should forward, print, copy, or otherwise reproduce this message in any manner that would allow it to be viewed by any individual not originally listed as a recipient. If the reader of this message is not the intended recipient, you are hereby notified that any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is strictly prohibited. If you have received this communication in error, please immediately notify the sender and delete this message.

**Comment by matteosister** [comment] 2018-02-16 08:23
ok, perfect.
We are starting using it right now, so I just wanted to know if you were commited to go on with development. I suggest anyway to publish it on hex.pm as a 0.x, just to reserve the name, and to make it easier and safer to follow development, without fear on every new deploy.

Many thanks!!!

**Comment by cosmin-harangus** [comment] 2018-04-03 18:54
Hello,
The package is now available on Hex.pm here: https://hexdocs.pm/eximap/readme.html
Please note that it's still in early development and it is not production ready yet.
Any bug reports, PRs or improvements to documentation are always welcome.

Closing this issue for now.

**Closed as completed by cosmin-harangus** 2018-04-03 18:54 UTC
